services:
  everydaybible:
    build: .
    container_name: "everydaybible"
    restart: always
    environment:
      - PORT=2323
    ports:
      - "2323:2323"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "2323" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - "everydaybible"

networks:
  everydaybible:
    name: everydaybible